# Generated by Django 4.1 on 2022-09-22 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('contato_emergencia', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=5)),
                ('horario_de_trabalho', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admitido', models.DateTimeField(default=datetime.datetime.now)),
                ('ocorencias', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_funcionario.funcao')),
            ],
        ),
    ]
