# Generated by Django 4.1 on 2022-10-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto_cpf',
            field=models.FileField(blank=True, upload_to='funcionario/cpf'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto_funcionario',
            field=models.FileField(blank=True, upload_to='funcionario/funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto_rg',
            field=models.FileField(blank=True, upload_to='funcionario/rg'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_cartao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_cartao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
