# Generated by Django 4.1 on 2022-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0002_funcionario_cvv_funcionario_foto_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pix',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
