# Generated by Django 4.1 on 2022-10-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0003_funcionario_agencia_funcionario_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome_cartao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero_cartao',
        ),
    ]
