# Generated by Django 4.1 on 2022-08-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_tipousuario_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuario.tipousuario'),
        ),
    ]
