# Generated by Django 4.1 on 2022-08-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=40)),
                ('data_nacimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('perna_dominante', models.CharField(max_length=20)),
                ('matricula_escolar', models.CharField(blank=True, default='', max_length=100)),
                ('serie', models.CharField(blank=True, default='', max_length=20)),
                ('nivel_escolar', models.CharField(blank=True, default='', max_length=30)),
                ('naturalidade_uf', models.CharField(max_length=3)),
                ('cidade', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=40)),
                ('numero_casa', models.CharField(blank=True, max_length=40)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('whatsapp2', models.CharField(blank=True, max_length=15)),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone_responsavel', models.CharField(max_length=15)),
                ('telefone_responsavel2', models.CharField(blank=True, max_length=15)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('plano_saude', models.CharField(blank=True, default='', max_length=100)),
                ('alergia', models.CharField(blank=True, default='', max_length=200)),
                ('imagem', models.ImageField(blank=True, upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('video', models.FileField(upload_to='videos')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_atleta.atletas')),
            ],
        ),
        migrations.AddField(
            model_name='atletas',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app_atleta.posicao'),
        ),
        migrations.AddField(
            model_name='atletas',
            name='subDivisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_atleta.subdivisao'),
        ),
    ]
