# Generated by Django 4.1 on 2022-08-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='naturalidade_uf',
            field=models.CharField(max_length=5),
        ),
    ]
