# Generated by Django 4.1 on 2022-08-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_espaco', models.CharField(max_length=200)),
                ('tamanho_do_espaco', models.CharField(max_length=100)),
                ('filial', models.CharField(default='CEFAT', max_length=100)),
                ('codigo_do_Local', models.CharField(max_length=50)),
                ('descrição_do_Local', models.TextField(default='')),
                ('situação', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
