# Generated by Django 4.1 on 2022-09-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facilitis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Local',
        ),
    ]
