# Generated by Django 4.1 on 2022-09-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facilitis', '0003_niveldeocorrencia_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='endereco',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='telefone_contato',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='tipo_local',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
