# Generated by Django 4.1 on 2022-09-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facilitis', '0004_local_endereco_local_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='situação',
            field=models.BooleanField(),
        ),
    ]
