# Generated by Django 4.1 on 2022-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facilitis', '0005_alter_local_situação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='status',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='fase',
            field=models.CharField(default='P', max_length=2),
            preserve_default=False,
        ),
    ]
